?start: sum
    | NAME "~" sum -> tilde

?sum: product
    | sum "+" product -> add
    | sum "-" product -> sub

?product:atom
    | product "*" atom -> mul
    | product "/" atom -> div

?atom: NAME "(" paramaters? ")" -> func_call
    | NUMBER -> number
    | "-" atom -> neg
    | "(" sum ")"
    | NAME

paramaters: paramvalue ("," paramvalue)*

paramvalue:atom | sum

%import common.NUMBER
%import common.WS_INLINE
%import common.CNAME -> NAME

%ignore WS_INLINE